#!/usr/bin/env python3

from pathlib import Path
from time import time

archives = Path("/var/cache/apt/proxy")
cutoff = time() - 30 * 86400

if archives.is_dir():
    for f in archives.rglob("*.deb"):
        if f.stat().st_mtime < cutoff:
            print(f.relative_to(archives))
            f.unlink()
