#!/usr/bin/env python3

import os
from pathlib import Path
from time import time

cache_dir = Path(os.environ.get("CACHE_DIR", "/var/cache/apt/proxy"))
cutoff = time() - 30 * 86400

if cache_dir.is_dir():
    for f in cache_dir.rglob("*.deb"):
        if f.stat().st_mtime < cutoff:
            print(f.relative_to(cache_dir))
            f.unlink()
